### PR TITLE
homepage simplification

### PR DESCRIPTION
**Pull request by pliablepixels**

### CODE REVIEW

**Comment by kylejohnson** [comment]
OK, I looked this over.  
1. The donate and contact commits look great.
2. Hell, the downloads page makes more sense now, too.
3. I think I'll combine the donate and contact pages later on in order to save navigation space (and do a sever redirect as to not lose links)
4. The home page proper needs some more love.  I like the simplified lists, but they need some more design love.  The jumbotron looks OK, but the text is too unreadable.

With all that said, I'll merge, and we'll go from there.  Would like to save some of the text from the legacy home page, though I'm not sure where it goes.

**Comment by SteveGilvarry** [comment]
http://beautifulopen.com/ I will just leave this here....

**Comment by kylejohnson** [comment]
@SteveGilvarry Hey, that's a nice find.

**Comment by pliablepixels** [comment]
Should we switch themes and pick another one from http://jekyllthemes.org ?  Some of these themes already provide a good amount of design foo. I just set one up for zmNinja using a modified version of devAid http://pliablepixels.github.io

**Pull request merged**
